const String BACK_BUTTON_ACTION_NOTHING = "";
const String BACK_BUTTON_ACTION_TOGGLE_MUTE = "TOGGLE_MUTE";
const String BACK_BUTTON_ACTION_CLOCK = "CLOCK";
const String BACK_BUTTON_ACTION_SCREENSAVER = "SCREENSAVER";
const String BACK_BUTTON_ACTION_TV_SETTINGS = "TV_SETTINGS";
const String BACK_BUTTON_ACTION_FLAUNCHER_SETTINGS = "FLAUNCHER_SETTINGS";
const String BACK_BUTTON_ACTION_APP_DRAWER = "APP_DRAWER";
const String BACK_BUTTON_ACTION_SLEEP = "SLEEP";
